### ISSUE TITLE
Add some kind of notification in case of build fails

### ISSUE THREAD

**Issue by reinhapa** [adoptium/jmc-build#19]
In order to not having to check each day if the JMC build for failure, it would be great to have the build emitting an failure either via email or Slack.

**Comment by IamLRBA** [comment]
Hello @reinhapa ,
i believe to achieve automated failure notifications via email or Slack for the JMC build in the [adoptium/jmc-build](https://github.com/adoptium/jmc-build), GitHub Actions (which already supports notifications and integrations with both email and Slack) can be used.

I would like to be assigned so that i may try and solve the issue.
Thanks!

**Comment by IamLRBA** [comment]
@reinhapa  I just submitted a [PR](https://github.com/adoptium/jmc-build/pull/95) in regards to this issue, Please have a review.
Thanks!
